name: Create Release Candidate

description: Create Release Candidate

inputs:
  tag:
    required: true
    description: tag

runs:
  using: "composite"
  steps:
    - name: Git checkout
      uses: actions/checkout@v3
    
    # - name: Run script
    #   run: ./test.sh
    #   shell: bash

    - name: check rc and merge
      run: |
        #!/usr/bin/env bash

        git config user.name "GitHub Actions Bot"
        git config user.email "devops@atarb2b.com"
        git config pull.ff only       # fast-forward only

        get_hash() {
            git rev-parse --short "$1" || true
        }

        git branch --delete --remotes origin/main
        git branch -r | grep -v '\->' | while read remote; do git branch --track "${remote#origin/}" "$remote"; done
        git fetch --all
        git pull --all

        current_release_candidate=$(git branch -a | grep rc | head -n 1 | cut -c 18- 2>&1)
        current_release_candidate_hash=$(get_hash origin/$current_release_candidate)
        current_branch=$(git symbolic-ref --short HEAD)
        current_branch_hash=$(get_hash $current_branch)

        if [ -z "$current_release_candidate_hash" ]; then
            new_version=$(date +%s)
            git checkout -b rc/$new_version
            git push --set-upstream origin rc/$new_version
            new_rc_hash=$(get_hash rc/$new_version)

            if [ "$new_rc_hash" = "$current_branch_hash" ]; then
                echo "Nothin to merge. rc is equal to the base branch."
                exit 1
            fi
        else
            git checkout $current_release_candidate
            git merge $current_branch --no-edit --ff-only --no-commit --allow-unrelated-histories
            git commit -am "merge auto from ${current_branch}"
            git push origin $current_release_candidate
        fi
      shell: bash

    - name: Send Message to Slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{job.status}}
        username: "CREATE_RC|${{github.event.repository.name}}|rc/${{ inputs.tag }}"
        author_name: ${{github.workflow}}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest
      if: always()
