name: Create Release Candidate

description: Create Release Candidate

runs:
  using: "composite"
  steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Change Owner of Container Working Directory
      run: chown -R $(id -u):$(id -g) $PWD
      shell: bash

    - name: New RC Version
      id: version
      run: |
        npm install version
        echo "NEW_VERSION=$(npm version minor)" >> $GITHUB_OUTPUT
      shell: bash

    - id: check-branch-exists
      uses: GuillaumeFalourd/branch-exists@v1
      with:
        branch: ${{ steps.version.outputs.NEW_VERSION }}

    - if: steps.check-branch-exists.outputs.exists == 'true'
      run: |
        echo "exists"
      shell: bash

    - if: steps.check-branch-exists.outputs.exists == 'false'
      run: |
        echo " not exists"
        # git config user.name "GitHub Actions Bot"
        # git config user.email "devops@atarb2b.com"
        # echo "New Release Candidate is rc/$new_version"

        # git checkout -b rc/$new_version || echo
        # git push --set-upstream origin rc/$new_version || echo
      shell: bash
