name: Create Release Candidate

description: Create Release Candidate

runs:
  using: "composite"
  steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Change Owner of Container Working Directory
      run: chown -R $(id -u):$(id -g) $PWD
      shell: bash

    - name: Check Current Branch
      id: current
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "devops@atarb2b.com"
        echo "CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Check version
      id: versioning
      uses: AtarB2B/github-semantic-versioning-actions@main

    - id: check-branch-exists
      uses: GuillaumeFalourd/branch-exists@v1
      with:
        branch: ${{ steps.versioning.outputs.version }}

    - if: steps.check-branch-exists.outputs.exists == 'true'
      run: |        
        
        baseBranch=${{ steps.current.outputs.CURRENT_BRANCH }}
        secondaryBranch=rc/${{ steps.versioning.outputs.version }}

        commitDiffCount=''
        baseBranchPath=$(git branch -r | grep "$baseBranch" | xargs)
        secondaryBranchPath=$(git branch -r | grep "$secondaryBranch" | xargs)
        commitDiffCount=$(git log --oneline "$secondaryBranchPath" \^"$baseBranchPath" | wc -l)
        
        if [[ "$commitDiffCount" -eq 0 ]]; then
        
          echo "------------  NOTHING TO MERGE  ------------"
        
        else
          
          echo "------------  Open PR from ${{ steps.current.outputs.CURRENT_BRANCH }} to ${{ steps.versioning.outputs.version }}.  ------------"
          # gh pr create --base=rc/${{ steps.versioning.outputs.version }} --head=${{ steps.current.outputs.CURRENT_BRANCH }} --title="[FC] branch ${{ steps.current.outputs.CURRENT_BRANCH }} to RC/${{ steps.versioning.outputs.version }} " --body="Pull Request FC to RC"
        
        fi
      
      shell: bash

    - if: steps.check-branch-exists.outputs.exists == 'false'
      run: |
        echo "New Release Candidate is rc/${{ steps.versioning.outputs.version }}"
        git checkout main || echo
        git checkout -b rc/${{ steps.versioning.outputs.version }} || echo
        git push --set-upstream origin rc/${{ steps.versioning.outputs.version }} || echo
        
        # gh pr create --base=rc/${{ steps.versioning.outputs.version }} --head=${{ steps.current.outputs.CURRENT_BRANCH }} --title="[FC] branch ${{ steps.current.outputs.CURRENT_BRANCH }} to RC/${{ steps.versioning.outputs.version }} " --body="Pull Request FC to RC"

      shell: bash
