name: Create Release Candidate

description: Create Release Candidate

runs:
  using: "composite"
  steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Change Owner of Container Working Directory
      run: chown -R $(id -u):$(id -g) $PWD
      shell: bash

    - name: check rc and merge
      run: |
        #!/usr/bin/env bash

        git config user.name "GitHub Actions Bot"
        git config user.email "devops@atarb2b.com"
        
        current_fc=$(git rev-parse --abbrev-ref HEAD)
        current_fc_hash=$(git rev-parse --short $current_fc)
        current_rc=$(git branch -r --no-color | grep "rc" | head -n 1)        
        current_rc_hash=$(git rev-parse --short $current_rc)
        
        echo "Current Release Candidate is $current_rc - $current_rc_hash"
        echo "..............................."
        
        if [ "$current_fc_hash" = "$current_rc_hash" ]; then
          echo "ERROR......."
          exit 1
        fi
        

        echo "passei"

        
        if [ -z "$current_rc_hash" ]; then

            npm install version
            new_version=$(npm version minor)

            echo "New Release Candidate is rc/$new_version"

            git checkout -b rc/$new_version || echo
            git push --set-upstream origin rc/$new_version || echo

            echo "Open PR from $current_fc to rc/$new_version."
            gh pr create --base=rc/$new_version --head=$current_fc --title="[FC] branch $current_fc to RC/$new_version" --body="Pull Request FC to RC"

        else
            
            echo "The $current_rc alredy exists, opening pr."
            gh pr create --base=$current_rc --head=$current_fc --title="[FC] branch $current_fc to RC/$current_rc" --body="Pull Request FC to RC"

        fi
      shell: bash
