name: Create Release Candidate

description: Create Release Candidate

runs:
  using: "composite"
  steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Change Owner of Container Working Directory
      run: chown -R $(id -u):$(id -g) $PWD
      shell: bash

    - name: New RC Version
      id: version
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "devops@atarb2b.com"
        
        npm install version
        echo "NEW_VERSION=$(npm version minor)" >> $GITHUB_OUTPUT
      shell: bash

    - id: check-branch-exists
      uses: GuillaumeFalourd/branch-exists@v1
      with:
        branch: ${{ steps.version.outputs.NEW_VERSION }}

    - if: steps.check-branch-exists.outputs.exists == 'true'
      run: |
        CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
        echo "Open PR from $(CURRENT_BRANCH) to ${{ steps.version.outputs.NEW_VERSION }}."
        gh pr create --base=rc/${{ steps.version.outputs.NEW_VERSION }} --head=$CURRENT_BRANCH --title="[FC] branch $CURRENT_BRANCH to RC/${{ steps.version.outputs.NEW_VERSION }} " --body="Pull Request FC to RC"
      shell: bash

    - if: steps.check-branch-exists.outputs.exists == 'false'
      run: |
        echo "New Release Candidate is RC/${{ steps.version.outputs.NEW_VERSION }}"
        git checkout -b rc/${{ steps.version.outputs.NEW_VERSION }} || echo
        git push --set-upstream origin rc/${{ steps.version.outputs.NEW_VERSION }} || echo
      shell: bash
