name: Create Release Candidate

description: Create Release Candidate

runs:
  using: "composite"
  steps:
    - name: Git checkout
      uses: actions/checkout@v3
    
    - name: Run script
      run: ./.github/scripts/cd.sh
      shell: bash
