name: Caller Workflow

on:
  push:
    branches:
      - main

jobs:
  workflow-calling:
    uses: AtarB2B/github-versioning-automation-workflow/.github/workflows/versioning_automation.yml@v1.0.0
    secrets: inherit
